package com.utn.newsAPI.model;


import lombok.*;

import javax.persistence.*;
import java.util.List;

@RequiredArgsConstructor
@Data
@Entity
public class Author {
    @Id
    private String userName;
    private String fullName;
    private String password;

    @OneToMany(fetch = FetchType.EAGER)
        /*
       Related entities fetching strategy.
       EAGER: fetches all.
       LAZY: returns a ResultSet pointer.
               (Resultset: A table of data representing a database result set,
               which is usually generated by executing a statement that queries the database.)
    */
    @JoinColumn(name = "author_id") // Specifies the foreign key column
    private List<News> writtenNews;
}
