package com.utn.newsAPI.model;

import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.List;

@NoArgsConstructor
@Data
@Entity
public class Author {
    @Id
    private String userName;
    @NotNull(message = "userName field in Author is required.")
    private String fullName;
    @NotNull(message = "password field in Author is required")
    private String password;

    @OneToMany(fetch = FetchType.EAGER)
        /*
       Related entities fetching strategy.
       EAGER: fetches all.
       LAZY: returns a ResultSet pointer.
               (Resultset: A table of data representing a database result set,
               which is usually generated by executing a statement that queries the database.)
    */
    @JoinColumn(name = "author_id") // Specifies the foreign key column
    private List<News> writtenNews;
}
